#!/usr/bin/env python3

import argparse
import subprocess
import sys

import status
import init
import add
import commit
import diff
import log
import push
import pull
import ignore
import history

if __name__ == '__main__':
	parser = argparse.ArgumentParser(description="Human-oriented UI for git")
	subparsers = parser.add_subparsers(dest='command', help="Command to run", required=True)

	status.add_subparser(subparsers)
	init.add_subparser(subparsers)
	add.add_subparser(subparsers)
	commit.add_subparser(subparsers)
	diff.add_subparser(subparsers)
	log.add_subparser(subparsers)
	push.add_subparser(subparsers)
	pull.add_subparser(subparsers)
	ignore.add_subparser(subparsers)
	history.add_subparser(subparsers)

	args = parser.parse_args()

	module = __import__(args.command)
	getattr(module, 'main')(args)
